# Generated by Django 4.2.6 on 2023-10-07 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.plan'),
        ),
        migrations.AddField(
            model_name='service',
            name='plans',
            field=models.ManyToManyField(blank=True, to='Core.plan'),
        ),
    ]
