# Generated by Django 4.2.6 on 2023-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_project_plan_service_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
