# Generated by Django 4.2.6 on 2023-10-07 20:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_contactform_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='Soufiane Majdar', max_length=150)),
                ('website_name', models.CharField(default='Agency', max_length=150)),
                ('website_description', models.TextField(blank=True, null=True)),
                ('website_logo', models.ImageField(blank=True, null=True, upload_to='WebInfo/')),
                ('Hero_title', models.CharField(max_length=150)),
                ('Hero_description', models.TextField(blank=True, null=True)),
                ('Hero_image', models.ImageField(blank=True, null=True, upload_to='WebInfo/')),
                ('about_title', models.CharField(max_length=150)),
                ('about_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='WebInfo/')),
                ('Services_title', models.CharField(max_length=150)),
                ('Services_description', models.TextField(blank=True, null=True)),
                ('Portfolio_title', models.CharField(max_length=150)),
                ('Portfolio_description', models.TextField(blank=True, null=True)),
                ('Contact_title', models.CharField(max_length=150)),
                ('Contact_description', models.TextField(blank=True, null=True)),
                ('Location', models.TextField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
