# Generated by Django 4.2.6 on 2023-10-07 20:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_webinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='Contact_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='Hero_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='Portfolio_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='Services_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='website_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
