# Generated by Django 4.2.6 on 2023-10-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_service_projects_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150)),
                ('checked', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='recommended',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='items',
            field=models.ManyToManyField(blank=True, to='Core.item'),
        ),
    ]
