# Generated by Django 4.2.6 on 2023-10-08 15:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='Testimonial_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinfo',
            name='Testimonial_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
