# Generated by Django 4.2.6 on 2023-10-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_client_is_active_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
