# Generated by Django 4.2.6 on 2023-10-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
