# Generated by Django 4.2.6 on 2023-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_project_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('Completed', 'Completed'), ('Delevered', 'Delevered'), ('Pending', 'Pending'), ('Canceled', 'Canceled'), ('On Hold', 'On Hold'), ('On Hosting', 'On Hosting'), ('On Development', 'On Development'), ('On Design', 'On Design'), ('On Testing', 'On Testing'), ('On Maintenance', 'On Maintenance'), ('On Support', 'On Support'), ('On Review', 'On Review')], default='in_progress', max_length=20),
        ),
    ]
